src/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import (login_view, dashboard_view,
                            register_view, edit_view,
                            user_list_view, user_detail_view,
                            user_follow_view)
from accounts.utils import (MyPasswordChangeView, MyPasswordResetConfirmView, MyPasswordResetView)

app_name = 'accounts'


urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('edit/', edit_view, name='edit'),

    path('users/', user_list_view, name='user_list'),
    path('users/follow/', user_follow_view, name='user_follow'),
    path('users/<str:username>/', user_detail_view, name='user_detail'),
    # может user_follow нужно перед user_detail потому что он follow в url будет воспринимать как username

    # Аутентификация из коробки ----------------------------------
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Просто смена пароля -------------------------------------
    path('password-change/', MyPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Смена утерянного пароля -------------------------------------
    # урлы смены пароля по почте если забыл пароль и встроенные обработчики
    path('password-reset/', MyPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # смотри на шаблоны html в templates/registration/ ...reset...html
    # они связаны с встроенными обработчиками из коробки
    # и обрати внимание, что в settings мы подключили
    # EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    # это для того, чтобы посылать письма не на почту а в консоль
    # а так, надо конечно настраивать почту


]

src/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('images/', include('images.urls', namespace='images')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)),)
# по какой-то причине функция static подходит только для локальных серверов
# ее крайне нежелательно использовать в продакшене (а может и не получится)

# bookmarks_admin
# bookmarks_admin@yandex.ru
# mysite.com:8000

# --------------------------facebook application:
# http://mysite.com:8000/
# bookmarks
# ID приложения: 503791577470729
# https://developers.facebook.com/apps/503791577470729/settings/basic/

# http://mysite.com:8000/social-auth/complete/facebook/
# https://mysite.com:8000/social-auth/complete/facebook/


# --------------------------google application:
# nameappication - MyProject61365


# for sslserver (HTTPS):
# python manage.py runsslserver
# https://github.com/Kirill67tyar/django-sslserver



# -----------------Что нужно делать, чтобы bookmarklet работал:

# 1) заходишь в прогу ngok (C:\Users\User\Desktop\Job\usefull_progs\ngrok-stable-windows-386)
# 2) набираешь в консоли ngrok http 8000
# 3) полуаешь нечтно такое:
"""
    Web Interface                 http://127.0.0.1:4040
    Forwarding                    http://83b42dc00ec9.ngrok.io -> http://localhost:8000
    Forwarding                    https://83b42dc00ec9.ngrok.io -> http://localhost:8000
"""
# 4) меняешь старый хост на новый полученный, в 3 местах в проекте:
# - settings.py (ALLOWED_HOSTS)
# - images/templates/bookmarklet_launcher.js
# - static/js/bookmarklet.js
# 5) ...
# 6) PROFIT!!!

# https://83b42dc00ec9.ngrok.io/accounts/login/
# https://438e2043a0d4.ngrok.io/accounts/login/
# https://f329b1815187.ngrok.io/accounts/login/

src/images/urls.py
from django.urls import path
from images.views import (create_view, detail_view,
                          my_detail_view, like_view,
                          experiment, list_view,
                          image_ranking, set_likes,)

app_name = 'images'


urlpatterns = [
    path('create/', create_view, name='create'),

    # для обработчика из книги
    path('detail/<int:id>/<slug:slug>/', detail_view, name='detail'),
    # OR
    # для моего обработчика
    # path('detail/<int:id>/<slug:slug>/', my_detail_view, name='detail'),

    path('list/', list_view, name='list'),
    path('like/', like_view, name='like'),
    path('image-ranking/', image_ranking, name='image_ranking'),

    path('set-likes/', set_likes, name='set_likes'),


    # --------------------------------------------
    path('experiment/', experiment, name='experiment'),

]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Bookmarks{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bookmarklet.css' %}">
</head>
<body>
<div id="header">
    {% include '_inc/header.html' %}
</div>

{% if messages %}
{% include '_inc/messages.html' %}
{% endif %}

<div id="content">
    {% block content %}
    Some content
    {% endblock %}
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
       });

</script>
</body>
</html>

src/templates/exp.html
<ul class="menu">
        <li {% if section == 'dashboard' %} class="selected"{% endif %}>
        <a href="{% url 'accounts:dashboard' %}">My dashboard</a>
        </li>
        <li {% if section == 'images' %} class="selected"{% endif %}>
        <a href="#">Images</a>
        </li>
        <li {% if section == 'people' %} class="selected"{% endif %}>
        <a href="#">People</a>
        </li>
    </ul>


<ul class="menu">
        <li class="selected">
        <a href="{% url 'accounts:dashboard' %}">My dashboard</a>
        </li>
        <li>
        <a href="#">Images</a>
        </li>
        <li>
        <a href="#">People</a>
        </li>
    </ul>