src/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import (login_view, dashboard_view,
                            register_view, edit_view,
                            user_list_view, user_detail_view,
                            user_follow_view)
from accounts.utils import (MyPasswordChangeView, MyPasswordResetConfirmView, MyPasswordResetView)

app_name = 'accounts'


urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('edit/', edit_view, name='edit'),

    path('users/', user_list_view, name='user_list'),
    path('users/follow/', user_follow_view, name='user_follow'),
    path('users/<str:username>/', user_detail_view, name='user_detail'),
    # может user_follow нужно перед user_detail потому что он follow в url будет воспринимать как username

    # Аутентификация из коробки ----------------------------------
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Просто смена пароля -------------------------------------
    path('password-change/', MyPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Смена утерянного пароля -------------------------------------
    # урлы смены пароля по почте если забыл пароль и встроенные обработчики
    path('password-reset/', MyPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # смотри на шаблоны html в templates/registration/ ...reset...html
    # они связаны с встроенными обработчиками из коробки
    # и обрати внимание, что в settings мы подключили
    # EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    # это для того, чтобы посылать письма не на почту а в консоль
    # а так, надо конечно настраивать почту


]

src/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('images/', include('images.urls', namespace='images')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)),)
# по какой-то причине функция static подходит только для локальных серверов
# ее крайне нежелательно использовать в продакшене (а может и не получится)

# bookmarks_admin
# bookmarks_admin@yandex.ru
# mysite.com:8000

# --------------------------facebook application:
# http://mysite.com:8000/
# bookmarks
# ID приложения: 503791577470729
# https://developers.facebook.com/apps/503791577470729/settings/basic/

# http://mysite.com:8000/social-auth/complete/facebook/
# https://mysite.com:8000/social-auth/complete/facebook/


# --------------------------google application:
# nameappication - MyProject61365


# for sslserver (HTTPS):
# python manage.py runsslserver
# https://github.com/Kirill67tyar/django-sslserver



# -----------------Что нужно делать, чтобы bookmarklet работал:

# 1) заходишь в прогу ngok (C:\Users\User\Desktop\Job\usefull_progs\ngrok-stable-windows-386)
# 2) набираешь в консоли ngrok http 8000
# 3) полуаешь нечтно такое:
"""
    Web Interface                 http://127.0.0.1:4040
    Forwarding                    http://83b42dc00ec9.ngrok.io -> http://localhost:8000
    Forwarding                    https://83b42dc00ec9.ngrok.io -> http://localhost:8000
"""
# 4) меняешь старый хост на новый полученный, в 3 местах в проекте:
# - settings.py (ALLOWED_HOSTS)
# - images/templates/bookmarklet_launcher.js
# - static/js/bookmarklet.js
# 5) ...
# 6) PROFIT!!!

# https://83b42dc00ec9.ngrok.io/accounts/login/
# https://438e2043a0d4.ngrok.io/accounts/login/
# https://f329b1815187.ngrok.io/accounts/login/

src/images/urls.py
from django.urls import path
from images.views import (create_view, detail_view,
                          my_detail_view, like_view,
                          experiment, list_view,
                          image_ranking, set_likes,)

app_name = 'images'


urlpatterns = [
    path('create/', create_view, name='create'),

    # для обработчика из книги
    path('detail/<int:id>/<slug:slug>/', detail_view, name='detail'),
    # OR
    # для моего обработчика
    # path('detail/<int:id>/<slug:slug>/', my_detail_view, name='detail'),

    path('list/', list_view, name='list'),
    path('like/', like_view, name='like'),
    path('image-ranking/', image_ranking, name='image_ranking'),

    path('set-likes/', set_likes, name='set_likes'),


    # --------------------------------------------
    path('experiment/', experiment, name='experiment'),

]

src/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User as U
User = settings.AUTH_USER_MODEL


class Profile(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Юзер')
    date_of_birth = models.DateField(blank=True, null=True, verbose_name='День рождения')
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, verbose_name='Фото')
    
    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        
    def __str__(self):
        return f'Profile for user {self.user.username}'




kwargs1 = {
    'to': User,
    'on_delete': models.CASCADE,
    'related_name': 'rel_from_set',
    'verbose_name': 'От юзера',
}
kwargs2 = kwargs1.copy()
kwargs2['related_name'] = 'rel_to_set'
kwargs2['verbose_name'] = 'К юзеру'



# В данном случае мы делаем промежуточную модель для ManyToMany
# Промежуточная модель необходима, когда нужно сохранить дополнительную
# информацию об отношениях (timestamp к примеру)
# но такая модель будет иметь и недостатки, будут отсутствовать
# встроенные методы ManyToMany методы add(), create(), remove()
# теперь нужно будет явно добавлять и удалять объекты промежутоной модели
# А вообще proxy таблица от django подходит в большинстве случаев
# определяется промежуточная модел примерно так:
"""
    models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False))
"""
# Вместо self может быть нужная модель
class Contact(models.Model):

    user_from = models.ForeignKey(**kwargs1)
    user_to = models.ForeignKey(**kwargs2)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано', db_index=True)

    def __str__(self):
        return f'{self.user_from} follow {self.user_to}'


# здесь мы прибавляем к нашей базовой модели User новое поле (аттрибут)
# сначала название поля, потом его значение.
# Лучше так динамически не прибавлять аттрибуты (поля)
# без видимых на то причин

# symmetrical=False здесь потому, привязываем поле manytomany на туже самую модель
# django воспроизводит семметриные отношения (дублирует запись?)
# при ссылке на self.
# symmetrical=False делает их несимметриными
U.add_to_class(
    'following',
    models.ManyToManyField(
        'self',
        through=Contact,
        related_name='followers',
        symmetrical=False))


# аргументы add_to_class - cls, name, value

# Алгоритм создания своей промежуточной модели:
# 1) Создаем свою модель с двумя ForeignKey на нужные модели
# 2) Создаем в одной из связанных моделей поле ManyToManyField
# 3) Указываем нашу промежуточную модель в именованном аргументе through= в ManyToMany

src/accounts/forms.py
from django.contrib.auth.models import User
from django.forms import (Form, ModelForm, CharField, PasswordInput, ValidationError, TextInput)
from accounts.models import Profile

attrs = {
    'attrs': {
        'placeholder': 'Enter username or email'
    }
}

class LoginForm(Form):

    username = CharField(required=True, label='Имя пользователя или email', widget=TextInput(**attrs))
    password = CharField(required=True, label='Пароль', widget=PasswordInput)


class RegisterModelForm(ModelForm):

    password = CharField(widget=PasswordInput, label='Введите пароль')
    password2 = CharField(widget=PasswordInput, label='Введите пароль еще раз')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email',)

    def clean_password2(self):
        cd = self.cleaned_data
        if cd.get('password') != cd.get('password2'):
            raise ValidationError('Пароли должны совпадать')
        return cd.get('password2')


class UserEditModelForm(ModelForm):

    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'email',



class ProfileEditModelForm(ModelForm):

    class Meta:
        model = Profile
        fields = 'date_of_birth', 'photo',

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, decorators, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User as U
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_POST

from accounts.forms import LoginForm, RegisterModelForm, ProfileEditModelForm, UserEditModelForm
from accounts.models import Profile, Contact
from actions.models import Action
from actions.utils import create_action
from common.decorators import ajax_required
from images.utils import get_view_at_console

User = get_user_model()

def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            print(f'\n\n$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\n'
                  f'LoginForm(request.POST) - {form}'
                  f'\n$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\n\n')
            print(f'\n\n########################################\n'
                  f'request.POST - {request.POST}'
                  f'\n########################################\n\n')
            if form.is_valid():
                print(f'\n\n*************************************\n'
                      f'LoginForm(request.POST).is_valid() - {form}'
                      f'\n\n\n*************************************\n\n\n')
                data = form.cleaned_data
                username = data['username']
                password = data['password']
                user = authenticate(request, username=username, password=password)
                print(f'\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n'
                      f'authenticate(request, username=username, password=password) - {user}'
                      f'\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n\n')
                if user:
                    if user.is_active:
                        login(request, user)
                        # get_view_at_console(request.GET)
                        return redirect(reverse('accounts:dashboard'))
                    else:
                        return HttpResponse('User is not active')
                else:
                    return HttpResponse('Invalid login/password')
        else:
            form = LoginForm()
            print(f'\n\nUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\n'
                  f'LoginForm().is_valid() - {form}'
                  f'\n\n\nUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\n\n\n')
        return render(request, 'accounts/login.html', {'form': form, })
    else:
        return HttpResponse('You already authenticated')

# как мы сможем попасть на запрашиваемую страницу после атентификации?
# с помощью поля <input type="hidden" name="next" value="{{next}}"/> в html форме login
@login_required
def dashboard_view(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
    actions = actions.select_related('user', 'user__profile').prefetch_related('target')
    paginator = Paginator(actions, 6)
    num_page = request.GET.get('page')
    try:
        actions = paginator.page(num_page)
    except PageNotAnInteger:
        actions = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        else:
            actions = paginator.page(paginator.num_pages)
    context = {
        'section': 'dashboard',
        'actions': actions,
    }
    if request.is_ajax():
        template_name = 'actions/action/actions_list.html'
    else:
        template_name = 'accounts/dashboard.html'
    return render(request, template_name=template_name, context=context)


def register_view(request):
    if request.method == 'POST':
        form = RegisterModelForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_user = form.save(commit=False)
            new_user.set_password(cd['password'])
            Profile.objects.create(user=new_user)
            create_action(new_user, 'Has created an account')
            new_user.save()
            return render(request, 'accounts/register_done.html', {'new_user': new_user,})
    else:
        form = RegisterModelForm()
    return render(request, 'accounts/register.html', {'form': form,})

@login_required
def edit_view(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            print(f'\n\n)))))))))))))))))))))))))))\n'
                  f'request.POST - {request.POST}'
                  f'\n))))))))))))))))))))))))))))\n\n')
            user_form = UserEditModelForm(instance=request.user, data=request.POST)
            profile_form = ProfileEditModelForm(instance=request.user.profile, data=request.POST, files=request.FILES)
            if user_form.is_valid() and profile_form.is_valid():
                user_form.save()
                profile_form.save()
                messages.success(request=request, message='Profile updated successfully')
                return render(request=request, template_name='accounts/edit_done.html', context={})
            else:
                messages.error(request=request, message='Error updating your profile')
        else:
            user_form = UserEditModelForm(instance=request.user)
            profile_form = ProfileEditModelForm(instance=request.user.profile)
        context = {
            'user_form': user_form,
            'profile_form': profile_form,
        }
        return render(request=request, template_name='accounts/edit.html', context=context)
    else:
        return redirect(reverse('accounts:login'))



@login_required
def user_list_view(request):
    users = User.objects.filter(is_active=True)
    context = {
        'users': users,
        'section': 'people',
    }
    return render(request, 'accounts/user/user_list.html', context=context)
    # return render(request, 'accounts/user/exp1.html', context=context)



@login_required
def user_detail_view(request, username):
    kwargs = {
        'klass': User,
        'username': username,
        'is_active': True,
    }
    user = get_object_or_404(**kwargs)
    context = {
        'user': user,
        'section': 'people',
        'image': user.profile.photo,
    }
    return render(request, 'accounts/user/user_detail.html', context=context)
    # return render(request, 'accounts/user/exp2.html', context=context)

@ajax_required
@require_POST
@login_required
def user_follow_view(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(pk=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                create_action(request.user, 'is_following', user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
        except User.DoesNotExist:
            pass
    return JsonResponse({'status': 'ok'})

src/accounts/templates/accounts/user/exp1.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}People{% endblock %}

{% block content %}
  <h1>People</h1>
  <div id="people-list">
    {% for user in users %}
      <div class="user">
        <a href="{{ user.get_absolute_url }}">
          {% thumbnail user.profile.photo "180x180" crop="100%" as im %}
            <img src="{{ im.url }}">
          {% endthumbnail %}
        </a>
        <div class="info">
          <a href="{{ user.get_absolute_url }}" class="title">
            {{ user.get_full_name }}
          </a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

src/accounts/templates/accounts/user/exp2.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ user.get_full_name }}{% endblock %}

{% block content %}
  <h1>{{ user.get_full_name }}</h1>
  <div class="profile-info">
    {% thumbnail user.profile.photo "180x180" crop="100%" as im %}
      <img src="{{ im.url }}" class="user-detail">
    {% endthumbnail %}
  </div>
  {% with total_followers=user.followers.count %}
    <span class="count">
      <span class="total">{{ total_followers }}</span>
      follower{{ total_followers|pluralize }}
    </span>
    <a href="#" data-id="{{ user.id }}" data-action="{% if request.user in user.followers.all %}un{% endif %}follow" class="follow button">
      {% if request.user not in user.followers.all %}
        Follow
      {% else %}
        Unfollow
      {% endif %}
    </a>
    <div id="image-list" class="image-container">
      {% include "images/image/list_ajax.html" with images=user.images_created.all %}
    </div>
  {% endwith %}
{% endblock %}

src/accounts/templates/accounts/user/user_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ user.username }}{% endblock %}

<!----------------------------------block content------------------------->
{% block content %}
<h1>{{ user.username }}</h1>

<div class="profile-info">
    {% thumbnail image "180x180" crop="100%" as im %}
    <a href="{{ image.url }}">
        <img src="{{ im.url }}" class="user-detail">
    </a>
    {% endthumbnail %}
</div>

{% with total_followers=user.followers.count  %}
<span class="count">
        <span class="total">
            {{ total_followers }}
        </span>
        follower{{ total_followers|pluralize }}
</span>

<!--user.followers.all вынести в отельную переменную-->
{% if request.user.pk != user.pk %}
{% with user_followers=user.followers.all %}
<a href="#"
   data-id="{{ user.pk }}"
   data-action="{% if request.user in user_followers %}un{% endif %}follow"
   class="follow button">
    {% if request.user not in user_followers %}
    Follow
    {% else %}
    Unfollow
    {% endif %}
</a>
{% endwith %}
{% endif %}

<div id="image-list" class="image-container">
    <!--очень классный пример использования with и другого шаблона
    с переопределением переменной в контексте-->
    {% include 'images/image/list_ajax.html' with images=user.images_created.all %}
</div>
{% endwith %}
{% endblock %}
<!----------------------------------endblock content------------------------->

<!----------------------------------block domready------------------------->
{% block domready %}
  $('a.follow').click(function(e){
    e.preventDefault();
    $.post('{% url "accounts:user_follow" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok') {
          var previous_action = $('a.follow').data('action');

          // toggle data-action
          $('a.follow').data('action',
            previous_action == 'follow' ? 'unfollow' : 'follow');
          // toggle link text
          $('a.follow').text(
            previous_action == 'follow' ? 'Unfollow' : 'Follow');

          // update total followers
          var previous_followers = parseInt(
            $('span.count .total').text());
          $('span.count .total').text(previous_action == 'follow' ? previous_followers + 1 : previous_followers - 1);
        }
      }
    );
  });
{% endblock %}
<!----------------------------------endblock domready------------------------->

src/accounts/templates/accounts/user/user_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}People{% endblock %}

{% block content %}
<h1>People</h1>
<div id="people-list">
    {% for user in users %}
    <div class="user">
        <a href="{{ user.get_absolute_url }}">

    {% thumbnail user.profile.photo "180x180" crop="100%" as im %}
            <a href="{{ user.get_absolute_url }}">
                <img src="{{ im.url }}">
            </a>
    {% endthumbnail %}

        </a>
        <div class="info">
            <a href="{{ user.get_absolute_url }}" class="title">
                {{user.username}}
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}